### ISSUE TITLE
Add support to add user's attributes

### ISSUE THREAD

**Issue by LloydNA** [rafaelcascalho/keycloak-middleware-ts#8]
I want to add attributes to an user since, for each user, I need to identify them with things like country, phone, etc.

**Comment by LloydNA** [comment]
I'll write the code, docs, and test for this issue, however, I am not able to modify the assignee of this repo's issues

**Comment by rafaelcascalho** [comment]
Sorry for the long wait, but I was finally able to find the time, to do the review, and it was solid. We should close this issue. Thanks a lot, @LloydNA :bow:
